### ISSUE TITLE
Config change from easydb5-master.yml to individual files is not documented

### ISSUE THREAD

**Issue by matsimon** [programmfabrik/easydb-documentation#7]
Most options are now handled (based on easyDB 5.46) to be done in distinct configuration files and easydb5-master.yml isn't required anymore. However no indication is given if the old config file still works along the new structure or whether it is defunct with a certain version of easydb.

Please document the version when the new configuration structure was _introduced_, when it becomes _required_ and at what version is becomes the only way to configure easydb 5. IMO this should be both present in the changelog section as well as in the configuration section.

Why you may ask: When upgrading leads to broken setup, such changes should be documented in order for system administrator to prepare for breaking changes and prepare / test configuration conversions ahead.

**Comment by KlausThornProgrammfabrik** [comment]
Dear Mathieu,

there is no indication about easydb5-master.yml becoming obsolete because it is still valid and there is currently no date when it will become obsolete. It is considered "the old style" and less flexible, though.

The only changes needed are in https://docs.easydb.de/en/releases/5.44/#configuration-changes

This also is the version of the easydb when the new configuration files were introduced.

We are currently working on the documentation of the configuration:

Does this help you to get an overview... https://docs.easydb.de/en/sysadmin/konfiguration/  ...?

Kind regards,
Klaus Thorn, Programmfabrik GmbH
